# Generated by Django 3.2.16 on 2022-11-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('population', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50, unique=True)),
                ('pathogen', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('disease_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PublicServant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('salary', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.country')),
            ],
        ),
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.diseasetype')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_death', models.PositiveIntegerField()),
                ('total_patients', models.PositiveIntegerField()),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.disease')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.publicservant')),
            ],
        ),
        migrations.AddField(
            model_name='publicservant',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.users'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.users'),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_type', to='diseases.diseasetype'),
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered', models.DateField()),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.disease')),
            ],
        ),
    ]
